services:
  app:
    build: .
    container_name: app-jobsearch
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobsearch
      SPRING_DATASOURCE_USERNAME: jobsearch
      SPRING_DATASOURCE_PASSWORD: jobsearch
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:16-alpine
    container_name: jobsearch-db
    environment:
      POSTGRES_DB: jobsearch
      POSTGRES_USER: jobsearch
      POSTGRES_PASSWORD: jobsearch
    volumes:
      - jobsearch_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jobsearch -d jobsearch" ]
      interval: 5s
      timeout: 3s
      retries: 20

  prometheus:
    image: prom/prometheus:v3.5.1
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-oss:11.5.0
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - jobsearch_grafana:/var/lib/grafana
    depends_on:
      - prometheus

  promtail:
    image: grafana/promtail:3.6.0
    container_name: promtail
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./observability/promtail.yml:/etc/promtail/promtail.yml:ro
      - ./logs:/var/log/jobsearch:ro
      - promtail_positions:/tmp
    depends_on:
      - loki

  loki_init:
    image: alpine:3.20
    user: "0:0"
    command: [ "sh", "-c", "mkdir -p /loki && chown -R 10001:10001 /loki" ]
    volumes:
      - loki_data:/loki

  loki:
    image: grafana/loki:3.6.0
    container_name: loki
    command: -config.file=/etc/loki/loki.yml
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./observability/loki.yml:/etc/loki/loki.yml:ro
      - loki_data:/loki
    depends_on:
      - loki_init
  frontend:
    build: ./frontend
    container_name: jobsearch-frontend
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - app
    restart: unless-stopped
volumes:
  jobsearch_pgdata:
  jobsearch_grafana:
  prometheus_data:
  promtail_positions:
  loki_data: