services:
  app:
    image: ${REGISTRY_IMAGE}:${IMAGE_TAG:-latest}
    build:
      context: ${BUILD_CONTEXT}
    container_name: app-jobsearch
    ports:
      - "${APP_BIND}:${APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${LOG_DIR}:${DOCKER_LOG_DIR}

  db:
    image: postgres:16-alpine
    container_name: jobsearch-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - jobsearch_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 20

  prometheus:
    image: prom/prometheus:v3.5.1
    container_name: prometheus
    ports:
      - "${APP_BIND}:${PROM_PORT}:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-oss:11.5.0
    container_name: grafana
    ports:
      - "${APP_BIND}:${GRAFANA_PORT}:3000"
    volumes:
      - jobsearch_grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=${GF_SERVER_SERVE_FROM_SUB_PATH}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
    depends_on:
      - prometheus

  promtail:
    image: grafana/promtail:3.6.0
    container_name: promtail
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./observability/promtail.yml:/etc/promtail/promtail.yml:ro
      - ${LOG_DIR}:/var/log/jobsearch:ro
      - promtail_positions:/tmp
    depends_on:
      - loki

  loki_init:
    image: alpine:3.20
    user: "0:0"
    command: [ "sh", "-c", "mkdir -p /loki && chown -R 10001:10001 /loki" ]
    volumes:
      - loki_data:/loki

  loki:
    image: grafana/loki:3.6.0
    container_name: loki
    command: -config.file=/etc/loki/loki.yml
    ports:
      - "${APP_BIND}:${LOKI_PORT}:3100"
    volumes:
      - ./observability/loki.yml:/etc/loki/loki.yml:ro
      - loki_data:/loki
    depends_on:
      - loki_init

  frontend:
    profiles: ["local"]
    build: ../frontend
    container_name: jobsearch-frontend
    ports:
      - "${APP_BIND}:${FRONT_PORT}:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  jobsearch_pgdata:
  jobsearch_grafana:
  prometheus_data:
  promtail_positions:
  loki_data: